### PR TITLE
Auto-change the theme based on time or OS' preference

### PR DESCRIPTION
**Pull request by Thealf154**

### CODE REVIEW

**Comment by migueravila** [comment]
Hi! @Thealf154 I loved the idea and It could be an awesome feature. But it also needs to be explained in the REAMDE. If you could also make the documentation of it I would love it. So I can accept the PR as quick as possible.

**Review by migueravila — CHANGES_REQUESTED** [review]
Loved the code. It needs README description.

**Comment by Thealf154** [comment]
Sure, i'll add it at the final of the README if you don't mind.

**Comment by Thealf154** [comment]
Done. Let me know if you liked my documentation.

**Review by migueravila — APPROVED** [review]

**Comment by migueravila** [comment]
Awesome job @Thealf154 this feature is fantastic!

**Pull request merged**
