### PR TITLE
Add Docker support (and docker-compose)

### PR DESCRIPTION
**Pull request by lewisdoesstuff**
I'm running this in a container myself, so I've published this [lewisdoesstuff/bento](https://hub.docker.com/r/lewisdoesstuff/bento).

I'm willing to maintain this, no problem! 
Added instructions to the README with both `docker run` and `docker-compose` instructions. 

Fixed another typo in the README as well, so that's included here.

### CODE REVIEW

**Comment by migueravila** [comment]
HI @lewisdoesstuff I would love to see this project running. If you can send me a demo of what you're implementing I would be happy to add it!

**Comment by lewisdoesstuff** [comment]
It's already implemented ;) 
PR contains a Dockerfile to build the docker container (just nginx with the files copied to /usr/share/nginx/html)
Also contains a docker-compose to pull the image from dockerhub (published under[lewisdoesstuff/bento](https://hub.docker.com/r/lewisdoesstuff/bento)).

It's usable at the moment with the hosted file! You can find the setup details in the README in this commit.

Other than running in a container, this doesn't differ from the source.

**Comment by migueravila** [comment]
Perfect @lewisdoesstuff I'll merge it!

**Comment by lewisdoesstuff** [comment]
Sounds good! Many thanks :) 

I'm watching the repo so I'll keep the Docker image up to date with any changes to the codebase
#79 can be closed as well

**Pull request merged**
